name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to EC2 on push to main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy files to EC2 using SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."  # You can change this to the specific folder or files
          target: ${{ secrets.TARGET_DIR }}

      - name: Run remote commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            sudo mv ${{ secrets.TARGET_DIR }}/* /var/www/html/
